"""Integration tests: real Claude API calls.

These verify what unit tests cannot - that the model actually obeys the rules
in app/prompts.py. They are skipped by default:

    pytest                      # skipped
    pytest --run-integration    # run for real

They need a valid ANTHROPIC_API_KEY in your .env file. No key is ever
hardcoded here; it is read the same way the app reads it.
"""

from __future__ import annotations

import re

import pytest

from app.agent import generate_linkedin_post
from app.config import MissingAPIKeyError, get_anthropic_api_key

# Mirrors the "Avoid" list in app/prompts.py.
BANNED_PHRASES = (
    "in today's fast-paced world",
    "in an era where",
    "game-changer",
    "i'm thrilled to announce",
    "let's dive in",
    "delve into",
    "unlock the power of",
    "the future is here",
    "at the end of the day",
)

AI_MENTIONS = ("as an ai", "ai-generated", "generated by ai", "language model")

TITLE_PREFIXES = ("linkedin post", "post:", "here is", "here's", "title:")


def _has_api_key() -> bool:
    try:
        get_anthropic_api_key()
    except MissingAPIKeyError:
        return False
    return True


# Applied to every test in this module.
pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(
        not _has_api_key(),
        reason="no ANTHROPIC_API_KEY configured",
    ),
]


def _paragraphs(post: str) -> list[str]:
    """Split into paragraphs, ignoring a trailing hashtag-only line."""
    blocks = [b.strip() for b in post.split("\n\n") if b.strip()]
    return [b for b in blocks if not re.fullmatch(r"(#\w+\s*)+", b)]


def _emoji_count(post: str) -> int:
    return sum(1 for char in post if ord(char) > 0x2100)


# One API call per language, shared by every assertion in that language.
@pytest.fixture(scope="module")
def english_post() -> str:
    return generate_linkedin_post("remote onboarding for engineers", "English")


@pytest.fixture(scope="module")
def german_post() -> str:
    return generate_linkedin_post("why code reviews slow down", "German")


# ---------------------------------------------------------------------------
# Basic shape
# ---------------------------------------------------------------------------


def test_returns_a_non_empty_string(english_post: str) -> None:
    assert isinstance(english_post, str)
    assert len(english_post) > 200


# ---------------------------------------------------------------------------
# Prompt rules that can be checked mechanically
# ---------------------------------------------------------------------------


def test_has_two_to_four_paragraphs(english_post: str) -> None:
    """Rule 5."""
    count = len(_paragraphs(english_post))
    assert 2 <= count <= 4, f"expected 2-4 paragraphs, got {count}"


def test_avoids_generic_ai_phrases(english_post: str) -> None:
    """Rule 8."""
    lowered = english_post.lower()
    found = [p for p in BANNED_PHRASES if p in lowered]
    assert not found, f"banned phrases present: {found}"


def test_does_not_overuse_emojis(english_post: str) -> None:
    """Rule 9."""
    count = _emoji_count(english_post)
    assert count <= 2, f"too many emojis: {count}"


def test_never_mentions_being_ai_generated(english_post: str) -> None:
    """Rule 13."""
    lowered = english_post.lower()
    found = [p for p in AI_MENTIONS if p in lowered]
    assert not found, f"AI self-reference present: {found}"


def test_has_no_title_or_label(english_post: str) -> None:
    """Rule 14."""
    lowered = english_post.lower().lstrip()
    assert not lowered.startswith(TITLE_PREFIXES)


def test_is_not_wrapped_in_quotes(english_post: str) -> None:
    """Rule 15."""
    assert not english_post.startswith(('"', "'", "“"))
    assert not english_post.endswith(('"', "'", "”"))


# ---------------------------------------------------------------------------
# The language requirement (rule 1)
# ---------------------------------------------------------------------------


def test_writes_in_the_requested_language(german_post: str) -> None:
    """A German request must produce German, not English."""
    lowered = f" {german_post.lower()} "

    german_hits = sum(
        lowered.count(w)
        for w in (" der ", " die ", " das ", " und ", " nicht ", " ist ",
                  " ich ", " ein ", " mit ", " von ")
    )
    english_hits = sum(
        lowered.count(w)
        for w in (" the ", " and ", " is ", " that ", " with ", " this ")
    )

    assert german_hits > english_hits, (
        f"expected German (de={german_hits}, en={english_hits}):\n{german_post}"
    )


def test_german_post_also_respects_the_structure(german_post: str) -> None:
    count = len(_paragraphs(german_post))
    assert 2 <= count <= 4, f"expected 2-4 paragraphs, got {count}"
